# Generated by Django 6.0.5 on 2026-06-03 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ouvriers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('DEMI', 'Demi-journée'), ('CONGE', 'Congé')], default='PRESENT', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ouvrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='ouvriers.ouvrier')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('ouvrier', 'date')},
            },
        ),
    ]
