# Generated by Django 6.0.5 on 2026-06-03 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ouvrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('metier', models.CharField(choices=[('MACON', 'Maçon'), ('ELECTRICIEN', 'Électricien'), ('PLOMBIER', 'Plombier'), ('PEINTRE', 'Peintre'), ('CARRELEUR', 'Carreleur'), ('CHARPENTIER', 'Charpentier'), ('SOUDEUR', 'Soudeur'), ('MANOEUVRE', 'Manœuvre'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('prix_journee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
